<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'cart' => [[], ['_controller' => 'App\\Controller\\CartController::index'], [], [['text', '/cart']], [], [], []],
    'checkout' => [['cartId'], ['_controller' => 'App\\Controller\\CartController::checkout'], [], [['variable', '/', '[^/]++', 'cartId', true], ['text', '/checkout']], [], [], []],
    'new_product' => [[], ['_controller' => 'App\\Controller\\DummyProductController::new'], [], [['text', '/product/new']], [], [], []],
    'new_special_price' => [[], ['_controller' => 'App\\Controller\\DummyProductController::newSpecialPrice'], [], [['text', '/specialPrice/new']], [], [], []],
    'app_product_administration_index' => [[], ['_controller' => 'App\\Controller\\ProductAdministrationController::index'], [], [['text', '/product/administration/']], [], [], []],
    'app_product_administration_new' => [[], ['_controller' => 'App\\Controller\\ProductAdministrationController::new'], [], [['text', '/product/administration/new']], [], [], []],
    'app_product_administration_show' => [['id'], ['_controller' => 'App\\Controller\\ProductAdministrationController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product/administration']], [], [], []],
    'app_product_administration_edit' => [['id'], ['_controller' => 'App\\Controller\\ProductAdministrationController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/product/administration']], [], [], []],
    'app_product_administration_delete' => [['id'], ['_controller' => 'App\\Controller\\ProductAdministrationController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product/administration']], [], [], []],
    'app_homepage' => [[], ['_controller' => 'App\\Controller\\ProductCatalogController::homepage'], [], [['text', '/']], [], [], []],
    'app_browse' => [['slug'], ['slug' => null, '_controller' => 'App\\Controller\\ProductCatalogController::browse'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/browse']], [], [], []],
    'api_products_get_one' => [['id'], ['_controller' => 'App\\Controller\\ProductController::getProduct'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/api/products']], [], [], []],
    'app_product_show' => [['slug'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'slug', true], ['text', '/product']], [], [], []],
];
