<?php

namespace ContainerNd4H0jO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pscxy1WService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pscxy1W' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pscxy1W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cartManager' => ['privates', 'App\\Manager\\CartManager', 'getCartManagerService', true],
            'product' => ['privates', '.errored..service_locator.pscxy1W.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.pscxy1W": it references class "App\\Entity\\Product" but no such service exists.'],
        ], [
            'cartManager' => 'App\\Manager\\CartManager',
            'product' => 'App\\Entity\\Product',
        ]);
    }
}
