<?php

namespace ContainerNd4H0jO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P4X83ZTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p4X83ZT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p4X83ZT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'product' => ['privates', '.errored..service_locator.p4X83ZT.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.p4X83ZT": it references class "App\\Entity\\Product" but no such service exists.'],
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
        ], [
            'entityManager' => '?',
            'product' => 'App\\Entity\\Product',
            'productRepository' => 'App\\Repository\\ProductRepository',
        ]);
    }
}
