<?php

namespace ContainerNd4H0jO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__UKsXjcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..uKsXjc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..uKsXjc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CartController::checkout' => ['privates', '.service_locator.04ZWU26', 'get_ServiceLocator_04ZWU26Service', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.7MfkIaG', 'get_ServiceLocator_7MfkIaGService', true],
            'App\\Controller\\DummyProductController::new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\DummyProductController::newSpecialPrice' => ['privates', '.service_locator.VNGWLlv', 'get_ServiceLocator_VNGWLlvService', true],
            'App\\Controller\\ProductAdministrationController::delete' => ['privates', '.service_locator.YQV8pxl', 'get_ServiceLocator_YQV8pxlService', true],
            'App\\Controller\\ProductAdministrationController::edit' => ['privates', '.service_locator.p4X83ZT', 'get_ServiceLocator_P4X83ZTService', true],
            'App\\Controller\\ProductAdministrationController::index' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductAdministrationController::new' => ['privates', '.service_locator.VNGWLlv', 'get_ServiceLocator_VNGWLlvService', true],
            'App\\Controller\\ProductAdministrationController::show' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\ProductCatalogController::browse' => ['privates', '.service_locator.7uyQ2yM', 'get_ServiceLocator_7uyQ2yMService', true],
            'App\\Controller\\ProductController::getProduct' => ['privates', '.service_locator.OC2AG.K', 'get_ServiceLocator_OC2AG_KService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.pscxy1W', 'get_ServiceLocator_Pscxy1WService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\CartController:checkout' => ['privates', '.service_locator.04ZWU26', 'get_ServiceLocator_04ZWU26Service', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.7MfkIaG', 'get_ServiceLocator_7MfkIaGService', true],
            'App\\Controller\\DummyProductController:new' => ['privates', '.service_locator.l2QwsaZ', 'get_ServiceLocator_L2QwsaZService', true],
            'App\\Controller\\DummyProductController:newSpecialPrice' => ['privates', '.service_locator.VNGWLlv', 'get_ServiceLocator_VNGWLlvService', true],
            'App\\Controller\\ProductAdministrationController:delete' => ['privates', '.service_locator.YQV8pxl', 'get_ServiceLocator_YQV8pxlService', true],
            'App\\Controller\\ProductAdministrationController:edit' => ['privates', '.service_locator.p4X83ZT', 'get_ServiceLocator_P4X83ZTService', true],
            'App\\Controller\\ProductAdministrationController:index' => ['privates', '.service_locator.JeTwYn4', 'get_ServiceLocator_JeTwYn4Service', true],
            'App\\Controller\\ProductAdministrationController:new' => ['privates', '.service_locator.VNGWLlv', 'get_ServiceLocator_VNGWLlvService', true],
            'App\\Controller\\ProductAdministrationController:show' => ['privates', '.service_locator.iyEwlLH', 'get_ServiceLocator_IyEwlLHService', true],
            'App\\Controller\\ProductCatalogController:browse' => ['privates', '.service_locator.7uyQ2yM', 'get_ServiceLocator_7uyQ2yMService', true],
            'App\\Controller\\ProductController:getProduct' => ['privates', '.service_locator.OC2AG.K', 'get_ServiceLocator_OC2AG_KService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.pscxy1W', 'get_ServiceLocator_Pscxy1WService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\CartController::checkout' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\DummyProductController::new' => '?',
            'App\\Controller\\DummyProductController::newSpecialPrice' => '?',
            'App\\Controller\\ProductAdministrationController::delete' => '?',
            'App\\Controller\\ProductAdministrationController::edit' => '?',
            'App\\Controller\\ProductAdministrationController::index' => '?',
            'App\\Controller\\ProductAdministrationController::new' => '?',
            'App\\Controller\\ProductAdministrationController::show' => '?',
            'App\\Controller\\ProductCatalogController::browse' => '?',
            'App\\Controller\\ProductController::getProduct' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CartController:checkout' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\DummyProductController:new' => '?',
            'App\\Controller\\DummyProductController:newSpecialPrice' => '?',
            'App\\Controller\\ProductAdministrationController:delete' => '?',
            'App\\Controller\\ProductAdministrationController:edit' => '?',
            'App\\Controller\\ProductAdministrationController:index' => '?',
            'App\\Controller\\ProductAdministrationController:new' => '?',
            'App\\Controller\\ProductAdministrationController:show' => '?',
            'App\\Controller\\ProductCatalogController:browse' => '?',
            'App\\Controller\\ProductController:getProduct' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
